### ISSUE TITLE
Question - OnState callback called for each transition

### ISSUE THREAD

**Issue by tskaufma** [cotestatnt/YA_FSM#1]
Hello,

 Is it intentional for the OnState callback to be called once for each transition defined? I was expecting OnState callback to be called once for each Update.

Thanks.

**Comment by cotestatnt** [comment]
Thanks to you for this report.

OnState callback function, if is defined, should be called inside[ bool YA_FSM :: Update ()] (https://github.com/cotestatnt/YA_FSM/blob/master/src/YA_FSM.cpp#L200), at line 200 of YA_FSM.cpp

I've just tried once again (and updated) the Blinky example and it works as expected.
Can you put the complete code with which you encountered this problem?

**Comment by christof62** [comment]
Hello,
In my opinion it is not useful to call OnState for each transition. Moving the call outside the for loop will fix this.
```
bool YA_FSM::Update(){
	bool stateChanged = false;

	for(FSM_Transition* actualtr = _firstTransition; actualtr != nullptr; actualtr = actualtr->nextTransition) {
        ...
	}
	if(_currentState->OnState != nullptr)
		_currentState->OnState();	
	return stateChanged;
}
```

**Comment by cotestatnt** [comment]
@christof62 I've done as you suggested.

Moreover, if a trigger condition is true, function will return without iterate the remaining states in order to avoid the possibility of two or more triggers during the same `Update()` call.
